concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    name: Integration Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.4.0
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      env:
        TZ: GMT
      id: build-test
      name: Build and run database integration tests
      run: "# Build\nmvn \\\n  --no-transfer-progress \\\n  --batch-mode \\\n  clean\
        \ package\n"
      shell: bash
    - continue-on-error: true
      id: install-graphviz
      name: Install Graphviz
      uses: sualeh/install-graphviz@v1.0.3
    - continue-on-error: true
      id: build-test-diagrams
      name: Build and run diagram tests
      run: "# Build\nmvn \\\n  --no-transfer-progress \\\n  --batch-mode \\\n  --projects\
        \ \\\n  schemacrawler-diagram,schemacrawler-scripting \\\n  --also-make \\\
        \n  package\n# Save expected results files\n.github/scripts/unit-tests-results-output.sh\n"
      shell: bash
    - continue-on-error: true
      id: upload-unit-tests-results-output
      if: always()
      name: Upload expected results files
      uses: actions/upload-artifact@v4
      with:
        name: unit-tests-results-output
        path: ./unit-tests-results-output.zip
        retention-days: 5
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 17
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
  build-test-docker:
    name: Build, run tests, and build Docker image
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: maximize-build-space
      name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-android: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
        remove-dotnet: 'true'
        remove-haskell: 'true'
        root-reserve-mb: '8192'
    - continue-on-error: true
      id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.4.0
      with:
        java-version: 8
    - continue-on-error: true
      id: install-graphviz
      name: Install Graphviz
      uses: sualeh/install-graphviz@v1.0.3
    - continue-on-error: true
      id: build-test
      name: Build Docker image
      run: "# Build\nmvn \\\n  --no-transfer-progress \\\n  --batch-mode \\\n  -Ddistrib\
        \ \\\n  -Ddocker.skip=false \\\n  clean package\n"
      shell: bash
name: Integration Tests
on:
  repository_dispatch:
    types: trigger-ga___integration-tests.yml
permissions: read-all
