concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    name: Lint code base
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: checkout-code
      name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: read-env
      name: Use super-linter environmental variables
      run: '# Use super-linter environmental variables

        cat .github/super-linter.env >> "$GITHUB_ENV"

        '
      shell: bash
    - continue-on-error: true
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: lint-code-base
      name: Lint Code Base
      uses: github/super-linter/slim@v5.0.0
    - continue-on-error: true
      id: strip-ansi-codes
      if: always()
      name: Strip ANSI codes from log
      run: '# Strip ANSI codes from log

        mv super-linter.log original-super-linter.log

        sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" original-super-linter.log
        > super-linter.log

        '
      shell: bash
    - continue-on-error: true
      id: persist-log
      if: false && always()
      name: Persist linter logs
      uses: actions/upload-artifact@v4
      with:
        name: super-linter-log
        path: super-linter.log
        retention-days: 9
name: Lint Code Base
on:
  repository_dispatch:
    types: trigger-ga___linter.yml
permissions: read-all
