concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    name: Publish Website
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.4.0
      with:
        java-version: 8
    - continue-on-error: true
      id: install-graphviz
      name: Install Graphviz
      uses: sualeh/install-graphviz@v1.0.3
    - continue-on-error: true
      id: build
      name: Build and test for distribution
      run: "# Build\nmvn \\\n  --no-transfer-progress \\\n  --batch-mode \\\n  -Ddistrib\
        \ \\\n  clean install\n"
      shell: bash
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      id: check-links
      name: Check website links
      uses: lycheeverse/lychee-action@v1.9.3
      with:
        args: --verbose --accept 200,999 --no-progress --base . `./schemacrawler-website/target/_website/**/*.html`
    - continue-on-error: true
      id: upload-link-check-report
      name: Upload website link check report
      uses: actions/upload-artifact@v4
      with:
        name: website-link-check-report.md
        path: ./lychee/out.md
        retention-days: 15
    - continue-on-error: true
      id: configure-pages
      name: Setup Pages
      uses: actions/configure-pages@v5
    - continue-on-error: true
      id: upload-artifact
      name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./schemacrawler-website/target/_website
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    name: Deploy Website
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: deploy-pages
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
name: Publish Website
on:
  repository_dispatch:
    types: trigger-ga___publish-website.yml
permissions:
  contents: read
  id-token: write
  pages: write
