concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    name: Quick build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.4.0
      with:
        java-version: 8
    - continue-on-error: true
      id: install-graphviz
      name: Install Graphviz
      uses: sualeh/install-graphviz@v1.0.3
    - continue-on-error: true
      id: build-test
      name: Build all modules and run tests
      run: "# Build\nmvn \\\n  --no-transfer-progress \\\n  --batch-mode \\\n  clean\
        \ package\n"
      shell: bash
name: Quick Build
on:
  repository_dispatch:
    types: trigger-ga___quick_build.yml
permissions: read-all
