concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    name: Build, run single-threaded database integration tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: maximize-build-space
      name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-android: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
        remove-dotnet: 'true'
        remove-haskell: 'true'
        root-reserve-mb: '8192'
    - continue-on-error: true
      id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.4.0
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      id: install-graphviz
      name: Install Graphviz
      uses: sualeh/install-graphviz@v1.0.3
    - continue-on-error: true
      env:
        SC_SINGLE_THREADED: true
        TZ: GMT
      id: build-test
      name: Build and run database integration tests
      run: "# Build\nmvn \\\n  --no-transfer-progress \\\n  --batch-mode \\\n  clean\
        \ package\n"
      shell: bash
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 17
name: Single-Threaded Database Integration Tests
on:
  repository_dispatch:
    types: trigger-ga___single-threaded-tests.yml
permissions: read-all
