concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build-test-coverage:
    name: Run coverage tests and publish results
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.4.0
      with:
        java-version: 11
    - continue-on-error: true
      id: install-graphviz
      name: Install Graphviz
      uses: sualeh/install-graphviz@v1.0.3
    - continue-on-error: true
      id: build-test
      name: Coverage tests
      run: "# Run coverage tests\nmvn \\\n  --no-transfer-progress \\\n  --batch-mode\
        \ \\\n  -Dtestcoverage \\\n  clean install\n"
      shell: bash
    - continue-on-error: true
      id: publish-coverage-codecov
      if: contains(github.ref, 'main')
      name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
    - continue-on-error: true
      env:
        CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
        CODACY_ORGANIZATION_PROVIDER: gh
        CODACY_PROJECT_NAME: SchemaCrawler
        CODACY_USERNAME: schemacrawler
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: publish-coverage-codacy
      if: contains(github.ref, 'main')
      name: Upload coverage report to Codacy
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        api-token: ${{ secrets.CODACY_API_TOKEN }}
    - continue-on-error: true
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      id: qodana-scan
      if: contains(github.ref, 'main')
      name: Qodana Scan
      uses: JetBrains/qodana-action@main
    - continue-on-error: true
      id: upload-coverage-test-results
      if: contains(github.ref, 'main')
      name: Upload coverage test results
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-coverage-test-results
        path: ./target/schemacrawler-jacoco.exec
        retention-days: 5
name: Test Coverage
on:
  repository_dispatch:
    types: trigger-ga___test-coverage.yml
permissions: read-all
